### PR TITLE
Rns 300 update sdk readme md with the new operations

### PR DESCRIPTION
**Pull request by OnyekaIjeh**

### CODE REVIEW

**Comment by sergio-jara** [comment]
After seeing the README. I noticed we require for the user to have the partnerConfiguration contract address. I know why we need it... but... Could we either provide the partner configuration in the constructor of the class or... CRAZY CRAZY CRAZY... not requiring the partner config contract at all?? like exposing it somehow? 👀. just to open the conversation.

**Comment by sergio-jara** [comment]
the Registrar has access to the PartnerManager. Maybe expose the partnerManager in the Registrar API? get the address from there and then get the partnerConfig contract from it? 
1. getPartnerManager
2. getPartnerConfig
3. partnerConfig

I know those are 3 requests... but given that registering a domain takes at least 30seconds... 500 miliseconds extra in the handshake doesnt sound crazy 👀

**Comment by sergio-jara** [comment]
regarding this PR in particular, I would just add the Renew function there and that should be it

**Comment by OnyekaIjeh** [comment]
Yes, I have been thinking about it.
It makes sense that you should be able to read the config right from the registrar.
Let's discuss it.

**Review by sergio-jara — APPROVED** [review]

**Pull request merged**
